In [1]:
!pip install jsonlines
import jsonlines
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
import pandas as pd
import numpy as np


In [5]:
url = 'https://raw.githubusercontent.com/AmbujaBudakoti27/Sarcasm-Detection/main/sarcasm_detection_shared_task_twitter_training.jsonl'
twitter_train=pd.read_json(url,lines=True)

In [6]:
twitter_train.head()

label  ...                                            context
0  SARCASM  ...  [A minor child deserves privacy and should be ...
1  SARCASM  ...  [@USER @USER Why is he a loser ? He's just a P...
2  SARCASM  ...  [Donald J . Trump is guilty as charged . The e...
3  SARCASM  ...  [Jamie Raskin tanked Doug Collins . Collins lo...
4  SARCASM  ...  [Man ... y ’ all gone “ both sides ” the apoca...

[5 rows x 3 columns]

In [7]:
twitter_train['response']=twitter_train['response'].str.replace('@USER', "") 
twitter_train['response']=twitter_train['response'].str.replace('\d+', '')
twitter_train['response']=twitter_train['response'].str.lower()
twitter_train['response']=twitter_train['response'].str.replace('[^\w\s]','')

In [8]:
twitter_train.head()

label  ...                                            context
0  SARCASM  ...  [A minor child deserves privacy and should be ...
1  SARCASM  ...  [@USER @USER Why is he a loser ? He's just a P...
2  SARCASM  ...  [Donald J . Trump is guilty as charged . The e...
3  SARCASM  ...  [Jamie Raskin tanked Doug Collins . Collins lo...
4  SARCASM  ...  [Man ... y ’ all gone “ both sides ” the apoca...

[5 rows x 3 columns]

In [9]:
twitter_train['context']=twitter_train['context'].apply(lambda x: ','.join(map(str, x)))
twitter_train['context']=twitter_train['context'].str.replace('@USER', "") 
twitter_train['context']=twitter_train['context'].str.lower()
twitter_train['context']=twitter_train['context'].str.replace('[^\w\s]','')
twitter_train['context']=twitter_train['context'].str.replace('\d+', '')

In [10]:
twitter_train.head()

label  ...                                            context
0  SARCASM  ...  a minor child deserves privacy and should be k...
1  SARCASM  ...    why is he a loser  hes just a press secretar...
2  SARCASM  ...  donald j  trump is guilty as charged  the evid...
3  SARCASM  ...  jamie raskin tanked doug collins  collins look...
4  SARCASM  ...  man  y  all gone  both sides  the apocalypse o...

[5 rows x 3 columns]

In [11]:
twitter_train.tail()

label  ...                                            context
4995  NOT_SARCASM  ...   apologies for the inconvenience you faced wit...
4996  NOT_SARCASM  ...    idk tho  i think i  m hungry  but that  s de...
4997  NOT_SARCASM  ...     peace to you  and two countries certainly s...
4998  NOT_SARCASM  ...  bernie sanders told elizabeth warren in privat...
4999  NOT_SARCASM  ...  pdp protest brainstorming session deji  we nee...

[5 rows x 3 columns]

In [15]:
from collections import Counter
Counter(twitter_train['label'])

Counter({'NOT_SARCASM': 2500, 'SARCASM': 2500})

In [14]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
corpus = []

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

for i in range(0, len(twitter_train)):
  m = re.sub('[^a-zA-Z]', ' ', twitter_train["response"][i])
  m = m.lower()
  m = m.split()
  m = [ps.stem(word) for word in m if not word in stopwords.words('english')]
  m =' '.join(m)
  corpus.append(m)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500)
X = cv.fit_transform(corpus).toarray()

In [31]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
y = pd.get_dummies(twitter_train['label'])
y = y.iloc[:,1].values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=uint8)

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [36]:
from sklearn.naive_bayes import MultinomialNB
sarcasm_detect_model_v1 = MultinomialNB().fit(X_train, y_train)
y_pred = sarcasm_detect_model_v1.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_v1 = accuracy_score(y_test, y_pred)

from sklearn.metrics import confusion_matrix
conf_v1 = confusion_matrix(y_test, y_pred)

In [37]:
sarcasm_detect_model_v1.score(X_test,y_test)

0.719

In [38]:
print("BOW and NaiveBayes\n")
print("accuracy: ", accuracy_v1, "\n")
print(conf_v1)

BOW and NaiveBayes

accuracy:  0.719 

[[364 155]
 [126 355]]


In [40]:
from sklearn.svm import SVC

model_linear_kernal = SVC(kernel='linear')
model_linear_kernal.fit(X_train, y_train)
model_linear_kernal.score(X_test, y_test)

0.716

In [41]:
model_sigmoid_kernal = SVC(kernel='sigmoid')
model_sigmoid_kernal.fit(X_train, y_train)
model_sigmoid_kernal.score(X_test, y_test)

0.695

In [42]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=20)
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [43]:
model.score(X_test, y_test)

0.681